Initial commit
MO-Movia/licit-color-picker pull request #1
Opened 2024-01-03 17:19 UTC by Jayakrishnan-MS

Reusable color picker library in all modules

2024-01-12 18:18 UTC, Tezra requested changes

2024-01-12 18:18 UTC, Tezra commented on README.md
> -# licit-color-picker
Was this change intended?

2024-01-12 18:18 UTC, Tezra commented on package.json
> +    "@testing-library/react": "^14.1.2",
This should be a devDependency

2024-01-31 21:03 UTC, Tezra requested changes
Needs more test coverage

2024-02-19 18:15 UTC, Tezra approved these changes

2024-02-19 20:47 UTC, rodgersgb approved these changes

2024-02-19 20:47 UTC, merged